export const AUTHENTICATION_LOGIN = "AUTHENTICATION_LOGIN";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT";
export const AUTHENTICATION_TOKEN_FROM_LS = "AUTHENTICATION_TOKEN_FROM_LS";
export const AUTHENTICATION_IS_EXPIRED = "AUTHENTICATION_IS_EXPIRED";
export const AUTHENTICATION_IS_NOT_EXPIRED = "AUTHENTICATION_IS_NOT_EXPIRED";

export const GET_BEACONS_API = "GET_BEACONS_API";
export const POST_BEACON_API = "POST_BEACON_API";
export const PUT_BEACON_IN_PROMOTION_API = "PUT_BEACON_IN_PROMOTION_API";

export const GET_PROMOTION_COURSES_API = "GET_PROMOTION_COURSES_API";
export const GET_COURSE_API = "GET_COURSE_API";
export const POST_COURSE_API = "POST_COURSE_API";
export const CLEAR_COURSE = "CLEAR_COURSE";

export const POST_EXCEPTION_API = "POST_EXCEPTION_API";
export const DELETE_EXCEPTION_API = "DELETE_EXCEPTION_API";

export const GET_COURSE_NOTES_API = "GET_COURSE_NOTES_API";
export const POST_NOTE_API = "POST_NOTE_API";

export const SET_PROMOTION = "SET_PROMOTION";
export const GET_PROMOTION_API = "GET_PROMOTION_API";
export const GET_PROMOTIONS_API = "GET_PROMOTIONS_API";
export const GET_PROMOTION_STATISTICS_API = "GET_PROMOTION_STATISTICS_API";

export const SET_YEAR = "SET_YEAR";
export const CLEAR_YEAR = "CLEAR_YEAR";
export const GET_YEAR_API = "GET_YEAR_API";

export const GET_STUDENT_API = "GET_STUDENT_API";
export const POST_STUDENT_API = "POST_STUDENT_API";
export const CLEAR_STUDENT = "CLEAR_STUDENT";
export const PATCH_STUDENT_STATUS_API = "PATCH_STUDENT_STATUS_API";

export const SET_STATISTICS_WS = "SET_STATISTICS_WS";
